### ISSUE TITLE
style guide y eslint

### ISSUE THREAD

**Issue by gaboesquivel** [CostaRicaJS/Fundamentos-de-JavaScript#32]
- [x] utilizar el [style guide de airbnb](https://github.com/airbnb/javascript)
- [x] configurar eslint para verificar que se siga el styleguide 
- [x] configurar travisCI
- [x] arreglar errores para que pasen los tests

**Comment by gaboesquivel** [comment]
estoy trabajando en eslint para markdown en este [branch](https://github.com/gaboesquivel/Fundamentos-de-JavaScript/tree/linting-markdown), estoy esperando resolver algunos problemas, apenas lo complete hago el pull request.

**Comment by stevengpa** [comment]
Gabo, tengo una duda con respecto a en si que es el formato Airbnb? A lo que pude observar es la forma en como esta estructurada la información, ejemplo:

1 jQuery
(cuando le damos click)
1 jQuery
  1.1 Prefix jQuery object variables with a $.
  1.2 Cache jQuery lookups.

... Sin embargo, este efecto se logra en el libro de manera automática al agregar un tema como Readme y los Subtemas ... no se si no capto la idea del formato Airbnb :disappointed:

**Comment by gaboesquivel** [comment]
seguir la guia de estilo de airbnb descrita en https://github.com/airbnb/javascript a la hora de escribir javascript.  en #33 agrego verificación con eslint, corriendo `npm test`  Ejemplo:
![](https://infinit.io/_/r3cMADT.png)

**Comment by stevengpa** [comment]
Hay una excepcion con el eslint en el file de composición.md el cual espera una asignacion o llamada de la funcion al momento de hacer la composicion, sin embargo, la asignacion se hace por Object.assign

18:1  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions

![image](https://cloud.githubusercontent.com/assets/10041338/10838500/cd35847c-7e8c-11e5-8321-c2e9e54e5a9b.png)

![image](https://cloud.githubusercontent.com/assets/10041338/10838506/f17340a4-7e8c-11e5-8dfa-f38f00e5f910.png)

**Comment by gaboesquivel** [comment]
1. John tiene que ser lowercase
2. tienes que llamar las funciones  caminar() y hablar(), falta los paréntesis

**Comment by stevengpa** [comment]
<h3>Error en reglas de Airbnb</h3>

``` javascript
const caminar = function caminar(nombre) {
  console.log(nombre + ' está caminando');
};

const hablar = function hablar(nombre) {
  console.log(nombre + ' está hablando');
};

const persona = function persona(nombre) {
  return Object.assign({}, caminar(nombre), hablar(nombre));
};

let jhon = persona('Jhon');
jhon.caminar; // Jhon está caminando
jhon.hablar;  // Jhon está hablando
```

<h3>Error en consola de Chrome y Babel Try out</h3>

``` javascript
const caminar = function caminar(nombre) {
  console.log(nombre + ' está caminando');
};

const hablar = function hablar(nombre) {
  console.log(nombre + ' está hablando');
};

const persona = function persona(nombre) {
  return Object.assign({}, caminar(nombre), hablar(nombre));
};

let jhon = persona('Jhon');
jhon.caminar(); // Jhon está caminando
jhon.hablar();  // Jhon está hablando
```

**Comment by gaboesquivel** [comment]
``` js
const caminador = (nombre) => ({
  caminar: () => console.log(nombre + ' está caminando')
});

const hablador = (nombre) => ({
  hablar: () => console.log(nombre + ' está hablando')
});

const persona = (nombre) => Object.assign({}, caminador(nombre), hablador(nombre));

const jhon = persona('Jhon');
jhon.caminar(); // Jhon está caminando
jhon.hablar();  // Jhon está hablando
```

**Comment by stevengpa** [comment]
Solucionado acá https://github.com/CostaRicaJS/Fundamentos-de-JavaScript/pull/42

**Comment by gaboesquivel** [comment]
Solucionado en #43
